ndlib/usurper

- src/components/Hours/Page/index.js
- src/components/Hours/Page/presenter.js
- src/components/LibMarkdown/index.js
- src/components/Link/index.js
- src/tests/components/Hours/Page/index.test.js
- add contentful sidebar to hours page
- add rewrite of all internal links to do actual internal link instead of redirect
eg. `alpha.library.nd.edu/biology` will be re-written to `/biology`
> Hours Sidebar + Link rewrites

- CHANGELOG.md
- src/components/Contentful/Building/index.js
- src/components/Contentful/Floor/presenter.js
- src/components/LandingPages/Services/index.js
- src/tests/components/Contentful/Building/presenter.test.js
Updated the floor page to display the call number range.  This included adding a field to the content type.
> Floor maps have callnumber ranges

- CHANGELOG.md
- src/actions/contentful/allAlerts.js
- src/components/Contentful/Alert/Global/index.js
- src/components/Contentful/Alert/Page/index.js
- src/components/Contentful/Alert/presenter.js
- src/components/Contentful/Page/presenter.js
- src/components/Header/index.js
- src/reducers/contentful/allAlerts.js
- src/reducers/index.js
- src/selectors/alerts.js
- src/static/css/global.css
- Pages have alerts below their title
- Global alerts show up between logo and nav
> Add alerts to pages and global

- src/components/LandingPages/Research/index.js
- src/components/Navigation/data/about.js
- src/components/Navigation/data/libraries.js
- src/components/Navigation/data/research.js
- src/components/SubjectList/index.js
> Fix some links and titles

- config/configurationGen.js
- src/components/Contact/index.js
- src/components/DatabaseList/index.js
- src/components/LandingPages/Research/index.js
- src/components/Librarians/presenter.js
- src/static/css/global.css
- update dev recommendation api
- add address to librarian contact info
- add catalog classic to research
> Links and Cleanup

- src/components/Hours/Current/index.js
- The hours api now gives us the utcOffset for the times at each location. Changed the timeToday to use this information to convert all times to local times before doing comparisons.
> Bugfix timezone offsets

- src/components/Navigation/data/services.js
catalog link to the wrong location
> Fix catalog link

- src/components/SearchDrawer/searchQueryBuilder.js
* Added an ampersand where one was missing in the search query builder.
> Fix ServiceNow Ticket INC0132626

- src/components/App/Rewrite/redirectRoutes.js
This now includes the form links. 
https://factotum.library.nd.edu/utilities/forms/purchase/new
> Make the deep linking more for factotum general.

- public/index.html
- src/components/Contentful/Page/presenter.js
- add ability to have arbitrary pathfinder related sections
- update hotjar code
> Arbitrary related resource sections

- src/tests/components/Courses/presenter.test.js
- Creates the test file for Courses/presenter.js
- Tests the enrollmentCard function and the instructorCard function separately
* by testing separately, the tests are leaner and yield same caliber test compared to testing 
together
- Tests with two different kinds of incorrect data
> Mh courses presenter test

- src/components/Footer/FooterLinks/index.js
This one is to fix the current released branch.
> Updated to the new link to service now form

- src/components/SearchDrawer/AdvancedSearch/AdvancedSearchTitle/index.js
- src/components/SearchDrawer/AdvancedSearch/SearchScope/index.js
- src/components/SearchDrawer/AdvancedSearch/SearchScope/presenter.js
- src/components/SearchDrawer/AdvancedSearch/presenter.js
- src/components/SearchDrawer/AdvancedSearch/style.css
- src/components/SearchDrawer/searchQueryBuilder.js
* Added extra field to display on advanced search for ND Catalog
* Also added “ND Catalog” and “OneSearch” title to Advanced Search
> Add Search Scope to ND Catalog

- config/configurationGen.js
- src/components/Footer/FooterLinks/index.js
- src/components/Messages/Error/index.js
- src/components/Messages/NotFound/index.js
- src/components/ServiceNowLink/index.js
Created a component to handle service now links and moved the base url into the configuration so that we can more easily change this if the form url changes again.
> Service now link

- config/webpack.config.dev.js
- src/components/Home/News/index.js
- src/components/ServiceNowLink/index.js
- show 3 most recent news entries on home page instead of timing out (sorted by starttime)
- fix node warnings
- fix css warnings
> News on Homepage

- src/tests/components/DatabaseList/index.test.js
- tests the DatabaseListContainer 
- makes sure it renders properly
- makes sure calls the bound fetchLetter action
> creates the DatabaseList test folder with the index test

- src/components/Messages/NotFound/index.js
* change to point to Library Website Content Review
* add the URL that resulted in the 404 page to the ticket
> Change link on 404 page

- CHANGELOG.md
- src/actions/personal/alephRenewal.js
- src/actions/personal/loanResources.js
- src/components/Hours/Current/expanded_presenter.js
- src/components/LoanResources/ResourceList/Resource/Actions/index.js
- src/components/LoanResources/ResourceList/Resource/Actions/presenter.js
- src/components/LoanResources/ResourceList/Resource/index.js
- src/components/LoanResources/ResourceList/Resource/presenter.js
- src/components/LoanResources/ResourceList/index.js
- src/components/LoanResources/ResourceList/presenter.js
- src/components/LoanResources/index.js
- src/components/LoanResources/presenter.js
- src/reducers/alephRenewal.js
- src/reducers/index.js
- src/static/css/global.css
- Add renew button to aleph items
- Add renew all button to top of checked out items
- Use custom action + reducer for reducers instead of the generic `personal` one
> Renew single and Renew All

- src/tests/components/DatabaseList/presenter.test.js
- tests every form of status, including null
- tests to make sure the correct html appears for each status
- tests when an incorrect letter.length is used (i.e. length>1)
> creates the presenter.test for DatabaseList

- src/actions/personal/alephRenewal.js
- src/actions/personal/loanResources.js
- src/actions/personal/settings.js
- src/components/App/index.js
- src/components/Dropdown/index.js
- src/components/Dropdown/presenter.js
- src/components/LoanResources/index.js
- src/components/Navigation/UserMenu/presenter.js
- src/components/Settings/index.js
- src/components/Settings/presenter.js
- src/components/Settings/settingsUpdateStatus.js
- src/reducers/index.js
- src/reducers/settings.js
- src/static/css/global.css
- Add Settings Page (no link, just go to `/settings`)
- Created generic dropdown component, very similar to search dropdown
- Added option to change preferred home library
> Settings Page

- src/components/Home/Events/index.js
- Preferring events in contentful will make sure they appear on the homepage
> Preferred events on homepage

- src/components/Settings/index.js
- src/components/Settings/presenter.js
- fix settings page to use split aleph/illiad queries (it only needs user info from aleph)
- Update library names to be uniform and compare with aleph correctly
> Settings Page updates

- src/components/SearchDrawer/AdvancedSearch/MaterialType/presenter.js
- src/components/SearchDrawer/AdvancedSearch/presenter.js
Modify the material type list in Advanced search to be different on ND
catalog per service now issue: INC0141679.
> INC0141679

- src/static/css/flexboxgrid.css
Fix issue with text getting cutoff on narrow display.
> INC0140120

- src/components/Home/Events/presenter.js
- src/components/Home/News/presenter.js
- src/static/css/global.css
Also removed event description per Andy's request
> Add links to news and events landing pages

- src/actions/contentful/databaseLetter.js
- src/components/DatabaseList/index.js
- src/components/DatabaseList/presenter.js
- src/reducers/contentful/databaseLetter.js
- src/tests/components/DatabaseList/index.test.js
- src/tests/components/DatabaseList/presenter.test.js
Add database search box to databases a-z page. 
- Query for all databases on load of any a-z page
- Search all databases by title
- Search results limited to 50
Also moved some logic out of presenter and into the container/mapping functions.
> Database search

- deploy/contentfulMigrations/addLibCalEventFields.js
- src/shared/ContentfulLibs.js
- Add a new contentful migration file
- update flatten local to work with empty strings
> Contentful changes

- src/components/DatabaseList/index.js
- src/components/DatabaseList/presenter.js
- src/components/LoanResources/ResourceList/Resource/presenter.js
- src/components/LoanResources/ResourceList/index.js
- src/components/LoanResources/ResourceList/presenter.js
- src/components/LoanResources/presenter.js
- src/static/css/global.css
- src/tests/components/LoanResources/resourcelist.test.js
- Accessibility text for the live filter searches on both the database list and items & requests pages. 
- Several other accessibility additions to the items & requests page
> Filter search accessability

- src/components/LibMarkdown/index.js
- src/static/css/global.css
style tables to be more grid-like - much nicer!
> Markdown tables

- src/static/css/global.css
see [this file](https://github.com/ndlib/usurper/blob/mobileMenuFix/src/components/Navigation/presenter.js#L85) for reference
> menu button wasn't showing up on mobile devices

- src/components/Footer/FooterInfo/ChatModal/index.js
> hide chat button on chat page

- src/components/SearchDrawer/AdvancedSearch/DateField/presenter.js
- src/components/SearchDrawer/AdvancedSearch/style.css
- src/static/css/global.css
CSS changes to make advanced search box easier to use on mobile.
Adds spacing around fields and makes sure related fields wrap sanely on small screens.
> Mobile Advanced Search

- src/components/Chat/index.js
Change the text from chat with librarian to chat with us.
> LW-140 update chat text

- src/components/Contentful/Page/columnPresenter.js
- src/components/Contentful/Page/sideNavPresenter.js
- src/components/Contentful/Page/style.css
Side navigation links to anchors on page.
> Adding side navigation to landing pages

- src/components/Header/BrandingBanner/index.js
- src/static/css/global.css
* Use div instead of h2 and h3 in the branding bar.
* Adjust styles to conform to change
> LW-148 Fix heading issue in theme

- src/shared/ContentfulLibs.js
Stop null values from throwing Errors when flattening contentful field locales
> Null Value Error check

- src/components/SearchDrawer/searchQueryBuilder.js
> Change advanced search default dates

- src/components/Contentful/Page/style.css
- src/static/css/global.css
per Melissa’s requests:
* update callout button with blue color
* change landing page grouping headers to blue with tdj
> CSS Changes

- CHANGELOG.md
- src/components/Contentful/Page/SideNav/index.js
- src/components/Contentful/Page/SideNav/presenter.js
- src/components/Contentful/Page/columnPresenter.js
- src/components/Contentful/Page/sideNavPresenter.js
- src/components/Contentful/Page/style.css
CSS alone can’t get this to behave the way we want.
> LW-161 Replace CSS "fixed" position with React-based positioning

- src/components/Home/Events/index.js
- src/static/css/global.css
- show full month and day in date
- always show minutes in time
- not all caps
> Event Date/Time Display

- src/components/DatabaseList/presenter.js
- src/components/FilterBox/index.js
- src/components/LoanResources/ResourceList/presenter.js
- src/components/LoanResources/presenter.js
- src/static/css/global.css
- make the filter display a component
- make the database letter filter a card
- conditionally add the `s` on `x items checked out` in the items page
LW-154 LW-156
> Filter Component

- src/components/DatabaseList/presenter.js
- src/static/css/global.css
> remove jesus from filters

- src/components/Contentful/ContactPoint/index.js
- src/components/Contentful/Page/presenter.js
NOTE: The big change in `Page/presenter.js` is just an indentation change.
> Make sure information order is as intended on mobile

- src/components/App/index.js
- src/components/Footer/FooterLinks/index.js
- src/components/SiteInfo/findIP.js
- src/components/SiteInfo/index.js
- src/components/SiteInfo/lastModified.js
- src/static/css/global.css
Create a new page that displays the following:
* Website version number
* Last modified date
* Client IP address
* Client user agent string
* Referring page path
* Screen dimensions
* Window dimensions
* React version
> LW-199 About this site

- src/components/Footer/FooterInfo/index.js
- src/components/Hours/Current/collapsed_presenter.js
- src/components/Hours/Page/style.css
Changed the colors on the hours and Spanish page to pass the color contrast test.
> Color Changed to Pass Contrast Test

- src/components/Footer/FooterInfo/index.js
Just switched Copyright from Role to ID as per request.
> Swiched from Role to ID

- src/components/Contentful/Page/columnPresenter.js
- src/components/Contentful/Page/style.css
A couple changes to the accessibility of the landing pages.
> Landing pages

- src/components/SearchDrawer/searchQueryBuilder.js
This was also an issue with CurateND search.
> LW-216 BUG - Primo search syntax in site search

- src/components/Hours/Page/style.css
- src/components/Hours/WeeklyHours/presenter.js
- src/static/css/global.css
See SN ticket:
https://nd.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=5cb3a6d5db
0f03007314fce9af961948%26sysparm_stack=incident_list.do%3Fsysparm_query=
active=true
* Fix positioning of long hours
* Fix padding issue on individual pages, but leave in place for hours
page.
> LW-235 BUG - Hours wrapping issue

- src/components/SearchDrawer/searchQueryBuilder.js
I broke the website search this fixes it.
> Fix the website search

- src/components/DatabaseList/presenter.js
- src/static/css/global.css
- src/static/images/more2.svg
- src/tests/components/DatabaseList/presenter.test.js
> database list look and feel and ellipsis updates

- src/components/Contentful/Event/presenter.js
- src/components/Contentful/News/presenter.js
- src/components/Contentful/Page/presenter.js
- src/components/Contentful/StaticContent/Body/presenter.js
Added a meta description using the short description field to 
Pages
Events
News
Dynamic Pages.
> LW-193 Added a meta description to each of the pages.

- src/components/App/index.js
- src/components/Embeddable/Hours/Current/index.js
- src/components/Embeddable/Hours/Current/presenter.js
- src/components/Embeddable/Hours/Current/style.css
- src/components/Embeddable/Hours/index.js
- src/components/Embeddable/Hours/presenter.js
- src/tests/components/Embeddable/Hours/Current/index.test.js
- src/tests/components/Embeddable/Hours/Current/presenter.test.js
* Create a version of the hours that can be included in an iFrame.
Works with the following servicePointIDs:
* hesburghlibrary
* askusdesk
* circulationservicedesk
* oitoutpost
* reservesmicrotextandmediadesk
* architecturelibrary
* mahaffeybusinesslibrary
* centerfordigitalscholarship
* chemistryphysicslibrary
* engineeringlibrary
* kelloggkroclibrary
* omearamathematicslibrary
* medievalinstitutelibrary
* byzantinestudiesreadingroom
* musiclibrary
* radiationchemistryreadingroom
* rarebooksspecialcollections
* universityarchives
* visualresourcescenter
> LW-236 Embeddable Hours

- src/components/Navigation/Menu/index.js
- src/static/css/global.css
> updated look for 'view more' buttons for consistency

- src/components/Hours/WeeklyHours/index.js
Change the hours hyphen to an en dash.
> lw-260 Change to an en dash

- src/components/Home/Events/presenter.js
- src/static/css/global.css
https://jira.library.nd.edu/browse/LW-259
> LW-259 - additional padding after last event

- deploy/contentfulMigrations/2018.01.15.addLibCalEventTimeLocFields.js
https://jira.library.nd.edu/browse/LW-255
> lw-255 - date, time, and location overrides for contentful events

- src/components/Contentful/Page/columnPresenter.js
> lw 252 - Update the navigation cards to allow items with no url.

- src/components/Contentful/News/presenter.js
- src/components/PageTitle/index.js
- src/static/css/global.css
- src/tests/components/PageTitle/index.test.js
Update news separator to be the same css as the events date/time separator.
> LW 263 Revised

- src/components/Contentful/Alert/alertHelpers.js
- src/components/Contentful/Alert/presenter.js
- src/static/css/global.css
- src/static/images/ic_info_outline_white_24px.svg
- Make the icons css background images instead of `<img>` tags so we can make sure wrapped text indents correctly.
- Alphabetically sort alerts if multiple have the same start time.
> LW-251.1 Update padding and sorting according to feedback

- src/components/Courses/presenter.js
- src/static/css/global.css
change how instructed courses are displayed so those who are both instructing and enrolled will see something more visually helpful
> Courses Layout

- deploy/contentfulMigrations/2018.02.02.addSponsoredBy.js
- src/components/Contentful/Event/presenter.js
- src/components/Sponsorships/index.js
- src/static/css/global.css
> Lw290 - indv event sponsorships

- src/actions/contentful/event.js
- src/components/Contentful/Event/index.js
- src/components/Contentful/Event/presenter.js
ensure that individual event pages show correct time - no timezone calculations
> Event timezone calculations

- deploy/contentfulMigrations/2018.02.08.reorderEventFields.js
delete hoursDisplay field, rename locations, and reorder
> event updates

- package.json
- src/components/DatabaseList/presenter.js
- src/static/css/global.css
- src/tests/components/DatabaseList/presenter.test.js
- yarn.lock
This allows for the ellipsis to be calculated with javascript.
> Add npm package to do the ellipsis

- src/components/Contentful/Event/presenter.js
Melissa would like this hidden until we fix a few more UI tweaks.
> remove presenters display

- src/components/Navigation/MobileMenu/index.js
- src/components/Navigation/index.js
- src/components/Navigation/presenter.js
* Add tab indexes when menu is visible.
* Always render menu, but hide it with css
> LW-223 - Main Menu Box Not Able to be Selected by Voice Over

- src/components/SearchDrawer/SearchBox/index.js
- src/components/SearchDrawer/SearchBox/presenter.js
- src/components/SearchDrawer/SearchOptionList/SearchOption/index.js
- src/components/SearchDrawer/SearchOptionList/SearchOption/presenter.js
- src/components/SearchDrawer/SearchOptionList/index.js
- src/tests/components/SearchDrawer/SearchOptionList/SearchOption/presenter.test.js
- src/tests/components/SearchDrawer/SearchOptionList/index.test.js
* Change how show/hide work
* Change tabIndexes: removed one that listed all children, toggle on show/hide
> LW-312 The search appliance is confusing in voice over mode.

- src/components/DatabaseList/Alphabet/index.js
- src/components/DatabaseList/presenter.js
- src/components/DatabaseList/style.css
- src/tests/components/DatabaseList/Alphabet/index.test.js
* Split Alphabet into separate component
* Modify css to move is and adjust display for lower screen resolutions.
> LW-315 Fix Database page letters disappear on screen sizes below 980px

- src/components/LandingPages/Contact/index.js
Add the music library to contact us
> Add music library

- src/components/Hours/Current/collapsed_presenter.js
- src/components/Hours/Current/expanded_presenter.js
- src/components/Hours/Page/presenter.js
our use of tab requires it is nested in a role='tablist'
> Try to fix the aria error

- src/components/App/index.js
- src/components/Navigation/presenter.js
- src/components/PageWrapper/presenter.js
Fixes:
* Warning: Unknown props `location`, `computedMatch` on \<div\> tag. Remove these props from the element.
* Warning: Failed prop type: The prop `loggedIn` is marked as required in `Navigation`, but its value is `undefined`.
> Fix a couple of console warnings

- src/components/LandingPages/Events/presenter.js
- src/components/Sponsorships/index.js
`<route>` without `<switch>` will just fall through all possible routes
> bugfix past event display and sponsorship display

- src/actions/personal/loanResources.js
- src/components/LoanResources/index.js
- src/tests/actions/personal/loanResources.test.js
- src/tests/components/LoanResources/index.test.js
To support these changes: https://github.com/ndlib/gatekeeper/pull/38
> Changes to support new gatekeeper api layout

- src/components/Navigation/MobileMenu/index.js
- src/components/Navigation/presenter.js
- src/static/css/global.css
Move hamburger to a different location to prevent collision with alerts. 
We need to have a larger discussion around placement, but this has been approved for now from POs.
> Hamburger move

- deploy/contentfulMigrations/2018.02.29.changeEventLocationToFullText.js
- src/components/Contentful/Event/presenter.js
- src/static/css/global.css
Will need to run the migration `forward` before deployment, and then `forward2` after deployment and confirmation that it's all good.
> Change event location field to be fulltext

- src/components/Chat/index.js
I updated the chat component to use the data from lib help rather than the style sheet we had before.
> Use the lib help template rather than our style sheet

- deploy/contentfulMigrations/2018.04.23.buildingPrimaryServicePoint.js
- src/components/Contentful/Floor/index.js
- src/components/Contentful/Floor/presenter.js
- src/static/css/global.css
- src/tests/components/Contentful/Floor/index.test.js
- src/tests/components/Contentful/Floor/presenter.test.js
This required adding a "Primary Service Point" to the "Building" type in Contentful to reference back to the service point.
> Update maps display to show primary service point information

- deploy/contentfulMigrations/2018.04.25.multipleAlertsOnPages.js
- src/components/Contentful/Alert/Page/index.js
- src/components/Contentful/Page/columnPresenter.js
- src/components/Contentful/Page/presenter.js
- src/components/Contentful/StaticContent/Alert/presenter.js
- src/static/css/global.css
Includes content types
- Pages
- Dynamic Pages
- Column Containers
Also altered the display of alerts on these pages so formatted better.
> Allow multiple alerts on pages

- src/components/Contentful/Event/presenter.js
- src/static/css/global.css
The headline image was 50%, which caused other things to align strangely
> quick fix for captions

- src/components/App/Rewrite/index.js
- src/components/Messages/Error/index.js
- src/components/Messages/NotFound/index.js
So that google will stop indexing everything!
> Add Prerender headers to error pages

- src/components/LandingPages/Events/Past/index.js
- src/components/LandingPages/Events/Past/presenter.js
- src/static/css/global.css
`static getDerivedStateFromProps` is the new react 16 lifecycle method replacing `componentWillRecieveProps`
> Add filter "search" to past events page

- src/components/SearchDrawer/searchQueryBuilder.js
- yarn.lock
Point to onesearchpprd instead of onesearch whenever not on the production site.
> LW-454 Change search box on dev-staging to point to onesearchpprd

- src/components/SearchDrawer/searchQueryBuilder.js
* Make changes to search query based on description provided by ExLibris and expand to make it compatible with observed behavior of advanced search in NUI.
* https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/050New_Primo_User_Interface/New_UI_Customization_-_Best_Practices#Creating_a_Search_Box_With_Deep_Links_to_the_New_UI
> LW-463 Reformat Advanced Search for NUI

- src/components/Contentful/Floor/SearchCallout/index.js
- src/components/Contentful/Floor/index.js
- src/components/Contentful/Floor/presenter.js
- src/components/FloorSearch/Empty/index.js
- src/components/FloorSearch/Empty/presenter.js
- src/components/FloorSearch/index.js
- src/tests/components/Contentful/Floor/index.test.js
- src/tests/components/Contentful/Floor/presenter.test.js
This is usurper work even though the ticket was put on the NUI board.  
I added a page called Empty for the no map search result. 
In general, the plan is to never see that page but just in case... now it does not say 404.
> NUI-151 Update the maps search to have an empty page.

- src/static/css/global.css
There is an overflow that extends off to the right of the screen. Fix this with a little CSS.
> LW-481 Mobile view isn't working properly

- src/components/SearchDrawer/AdvancedSearch/SearchScope/presenter.js
- src/components/SearchDrawer/searchQueryBuilder.js
> search scope

- src/actions/contentful/page.js
- src/components/Contentful/ColumnPage/presenter.js
- src/components/Navigation/MenuColumn/MenuList/index.js
* Added some additional existence checks before render(s)
* For some reason contentful direct does not like to have the preview parameter in the query string when it's false for pages.
* Reinclude "include" in query parameters to get depth on columnContainers.
> Some fixes for Contentful Direct on Column pages

- src/actions/contentful/allAlerts.js
- src/selectors/alerts.js
Update to have a cache breaker for alert requests so they are not responding to the 1hr cache
fix alerts data so it loads.
> Fix issue with alerts 

- src/components/SearchDrawer/searchQueryBuilder.js
Fix OneSeach to use the correct scope of malc_blended
> INC0205282 Fix search_scope for OneSearch tab

- src/components/APIPresenterFactory/index.js
- src/components/Contentful/Database/presenter.js
APIPresenterFactory cannot handle components created as classes, so we can't wrap in `withErrorBoundary`. Need to catch it in `<ErrorBoundary/>`
> fix database page

- src/actions/contentful/allAlerts.js
- src/actions/contentful/allEvents.js
- src/actions/contentful/allNews.js
- src/actions/contentful/databaseLetter.js
- src/actions/contentful/entry.js
- src/actions/contentful/event.js
- src/actions/contentful/floor.js
- src/actions/contentful/news.js
- src/actions/contentful/page.js
- src/actions/contentful/servicePoints.js
- src/actions/contentful/staticContent.js
preview is a directive for contentful direct not for the paramaters passed through to contentful.
> Fix preview links.

- public/index.html
> Google Site Verification

- src/actions/contentful/databaseLetter.js
- src/components/DatabaseList/index.js
remove the punctuation from the database searching
> Update db search to remove punct

- src/actions/contentful/servicePoints.js
- src/components/Contentful/ServicePoint/index.js
If the ServicePoint component receives a reference with an id but is missing the full details (fields), go and fetch the service point explicitly from Contentful.
> Show service point on floor map page according to the building it is in.

- src/components/SearchDrawer/AdvancedSearch/style.css
Adjusted the layout of the advanced search form.
> Advanced Search

- config/configurationGen.js
> Revert "New GCSE"

- config/configurationGen.js
It is restricted to *.library.nd.edu/*, so it will not work in localhost.
> Let's try this key

- .gitignore
- README.md
- buildspec.yml
- config/configurationGen.js
- deploy/deployWebsiteLocal.sh
- deploy/web/postDeploy.py
- scripts/build-links/buildConfig.js
- scripts/build-links/lib/getStage.js
- src/components/Contentful/Database/presenter.js
- src/components/LoanResources/CirculationHistory/presenter.js
- src/components/LoanResources/ResourceList/Resource/presenter.js
- src/components/SearchDrawer/searchQueryBuilder.js
Get environment-specific values from parameter store during deployment and put them in the config.
> LW-596 During deploy, update config based on environment.

- .travis.yml
- README.md
- package.json
- yarn.lock
This should add test coverage in code climate, reported through our Travis CI build.
> Add test coverage with code climate. Update jest.

- .eslintrc
- config/jest/fileTransform.js
- package.json
- src/actions/personal/courses.js
- src/components/Account/Courses/CourseList/CourseCard/PathFinders/index.js
- src/components/Account/Courses/CourseList/CourseCard/index.js
- src/components/Account/Courses/CourseList/index.js
- src/components/Account/Courses/CourseList/style.module.css
- src/components/Account/Courses/index.js
- src/components/Account/Courses/presenter.js
- src/static/css/global.css
- src/tests/actions/personal/courses.test.js
- src/tests/components/Account/Courses/CourseList/CourseCard/PathFinders/index.test.js
- src/tests/components/Account/Courses/CourseList/CourseCard/index.test.js
- src/tests/components/Account/Courses/CourseList/index.test.js
- src/tests/components/Account/Courses/index.test.js
- src/tests/components/Account/Courses/presenter.test.js
- yarn.lock
- Split out into subcomponents.
- Move CSS styles to a new file next to the component.
- Implement CSS modules.
- Expand/improve unit tests.
> LW-621 Refactor Courses components.

- src/components/Contentful/StaticContent/Alert/index.js
- src/components/Contentful/StaticContent/Body/index.js
- src/components/Contentful/StaticContent/Sidebar/index.js
- src/components/Hours/Page/index.js
- src/components/Hours/Page/presenter.js
- src/tests/components/Hours/Page/index.test.js
Also includes optimization to not fetch the same Dynamic Page from Contentful repeatedly when it is already in the store.
> LW-664 Fetch hours page title from contentful.

- src/components/Account/Favorites/Search/index.js
- src/components/Interactive/FilterBox/index.js
- src/components/Layout/SearchDrawer/AdvancedSearch/AdvancedSearchField/SearchInput/presenter.js
- src/components/Layout/SearchDrawer/AdvancedSearch/style.css
- src/components/Layout/SearchDrawer/SearchBox/presenter.js
This lets the browser handle the element better by adding an X button to easily clear the contents.
> Add input type of 'search' to search boxes.

- src/components/Interactive/FilterBox/index.js
- src/components/Interactive/FilterBox/style.module.css
- src/static/css/global.css
There will be more changes with this ticket, but this part was quick and easy.
> LW-701 Fix styling on filter box causing it to shrink too small.

- config/configurationGen.js
- scripts/build-links/buildConfig.js
- src/components/DatabaseList/Alphabet/index.js
- src/components/DatabaseList/Databases/index.js
- src/components/DatabaseList/SubjectFacets/index.js
- src/components/DatabaseList/SubjectFacets/presenter.js
- src/components/DatabaseList/SubjectFacets/style.module.css
- src/components/DatabaseList/index.js
- src/components/DatabaseList/presenter.js
- src/components/DatabaseList/style.module.css
- src/tests/components/DatabaseList/Alphabet/index.test.js
- src/tests/components/DatabaseList/Databases/index.test.js
- src/tests/components/DatabaseList/SubjectFacets/index.test.js
- src/tests/components/DatabaseList/SubjectFacets/presenter.test.js
- src/tests/components/DatabaseList/index.test.js
- src/tests/components/DatabaseList/presenter.test.js
This includes the basics for making subject filtering workable. Additional UI components are covered by other tickets.
> LW-633 Add UI for subject filtering on Databases.

- package.json
- yarn.lock
Since it's introducting it's own vulnverabilities and nobody likes it anyway, let's get rid of it.
> Remove Snyk

- src/components/Contentful/Alert/presenter.js
- src/static/css/global.css
- src/tests/components/Contentful/Alert/presenter.test.js
(Long text in Contentful model.)
> LW-708 Support markdown for alert descriptions. 

- src/components/App/index.js
- src/components/DatabaseList/ActiveFiltersList/index.js
- src/components/DatabaseList/Alphabet/index.js
- src/components/DatabaseList/Databases/DatabaseSummary/presenter.js
- src/components/DatabaseList/Databases/index.js
- src/components/DatabaseList/SubjectFacets/index.js
- src/components/DatabaseList/SubjectFacets/presenter.js
- src/components/DatabaseList/index.js
- src/components/DatabaseList/presenter.js
- src/components/DatabaseList/style.module.css
- src/components/Interactive/FilterBox/index.js
- src/components/Interactive/FilterBox/style.module.css
- src/constants/HelperFunctions.js
- src/static/css/global.css
- src/tests/components/App.test.js
- src/tests/components/DatabaseList/ActiveFiltersList/index.test.js
- src/tests/components/DatabaseList/Alphabet/index.test.js
- src/tests/components/DatabaseList/Databases/DatabaseSummary/presenter.test.js
- src/tests/components/DatabaseList/index.test.js
- src/tests/components/DatabaseList/presenter.test.js
Includes changes for:
- LW-732
- LW-733
- LW-734
- LW-735
- LW-736
- LW-737
- LW-738
The gist of it is, display the entire list of databases. Make letter filtering optional and additive on top of search and subject filters.
> Databases page tweaks

- src/components/Layout/SearchDrawer/AdvancedSearch/AdvancedSearchField/SearchInput/presenter.js
- src/components/Layout/SearchDrawer/AdvancedSearch/DateField/presenter.js
- src/components/Layout/SearchDrawer/searchQueryBuilder.js
Also disable auto-complete on search fields.
> LW-777 Fix advanced search scope.

- package.json
- src/components/DatabaseList/SubjectFacets/index.js
- src/components/DatabaseList/SubjectFacets/presenter.js
- src/components/DatabaseList/SubjectFacets/style.module.css
- src/components/DatabaseList/presenter.js
- src/components/DatabaseList/style.module.css
- src/tests/components/DatabaseList/SubjectFacets/index.test.js
- src/tests/components/DatabaseList/SubjectFacets/presenter.test.js
- yarn.lock
Apply subject filters automatically when clicking subject instead.
> LW-775 Remove Apply and Undo buttons from Databases page.

- src/actions/contentful/allAlerts.js
- src/actions/personal/settings.js
- src/components/Contentful/Alert/Global/index.js
- src/components/Contentful/Alert/Page/index.js
- src/components/Contentful/Alert/alertHelpers.js
- src/components/Contentful/Alert/presenter.js
- src/components/Contentful/Alert/style.module.css
- src/components/Layout/Header/index.js
- src/components/Messages/PageAlert/index.js
- src/selectors/alerts.js
- src/static/css/global.css
- src/tests/components/Contentful/Alert/Global/index.test.js
- src/tests/components/Contentful/Alert/Page/index.test.js
- src/tests/components/Contentful/Alert/presenter.test.js
- src/tests/components/Contentful/Page/presenter.test.js
- src/tests/reducers/contentful/allAlerts.test.js
- src/tests/selectors/alerts.test.js
Some refactoring and more unit tests to go along with it, of course.
> LW-769 Add ability to hide alerts.

- src/components/Account/Favorites/NoFavorites/index.js
- src/components/Account/Favorites/TopFavorites/index.js
- src/components/Contentful/ServicePoint/index.js
- src/components/Hours/Page/style.css
- src/static/css/global.css
- src/static/css/print.css
> LW-779, LW-780 Accessibility improvements

- config/configurationGen.js
- package.json
- scripts/buildConfig.js
- src/components/DatabaseList/Databases/DatabaseSummary/presenter.js
- src/components/LandingPages/Events/Wrapper/index.js
- src/components/LandingPages/Events/Wrapper/presenter.js
- src/tests/components/LandingPages/Events/Wrapper/presenter.test.js
Fix some display issues when subject filtering disabled.
> LW-805 Add flag for enabling events filtering.

- scripts/makeSitemap.js
> Changed exclude to account for missing files

- deploy/deployServicesLocal.sh
In the future, this will probably be removed in favor of using a pipeline for deploying these services. However, in the mean time, I thought it would be easier to deploy with this script since everything is all in one place and you don't need to remember different parameters.
> LW-837 Add deploying service with cdk.

- src/components/Contentful/Event/presenter.js
- src/static/css/global.css
Also fix some css which was causing the image to overlap share buttons.
> LW-833 Move view all events to bottom of events page on mobile view.

- package.json
- src/actions/contentful/floor.js
- src/actions/floorSearch.js
- src/components/Contentful/Floor/SearchCallout/index.js
- src/components/Contentful/Floor/index.js
- src/components/Contentful/Floor/presenter.js
- src/components/FloorSearch/Empty/index.js
- src/components/FloorSearch/Empty/presenter.js
- src/components/FloorSearch/index.js
- src/reducers/floorSearch.js
- src/tests/actions/contentful/floor.test.js
- src/tests/actions/floorSearch.test.js
- src/tests/components/Contentful/Floor/SearchCallout/index.test.js
- src/tests/components/Contentful/Floor/index.test.js
- src/tests/components/FloorSearch/Empty/index.test.js
- src/tests/components/FloorSearch/Empty/presenter.test.js
- src/tests/components/FloorSearch/index.test.js
- src/tests/reducers/contentful/floor.test.js
- src/tests/reducers/floorSearch.test.js
And extensive additions to unit tests, as it goes.
> LW-861 Support alternate service points on floor maps.

- src/static/css/global.css
Updating the table style globally ahead of LW-850. Will improve appearance of tables.
> LW-893 - Global table css update

- src/static/css/global.css
> LW-893: Global table css update

- src/components/Messages/NotFound/index.js
- src/tests/actions/contentful/allRedirects.test.js
- src/tests/components/Messages/NotFound/index.test.js
- src/tests/reducers/contentful/allRedirects.test.js
> LW-912 Redirect unit tests

- src/components/ChatPage/index.js
- src/components/Contentful/StaticContent/Body/index.js
- src/components/Contentful/StaticContent/Body/presenter.js
- src/tests/components/Chat/index.test.js
- src/tests/components/ChatPage/index.test.js
- src/tests/components/Contentful/StaticContent/Body/index.test.js
- src/tests/components/Contentful/StaticContent/Body/presenter.test.js
Also adds unit tests for all this since it did not have any.
> LW-933 Add Contentful content to chat page.

- src/components/Account/AccountPageWrapper/index.js
- src/components/Account/ItemsRequests/presenter.js
This also fixes Contentful preview on account pages.
> Fix slug for items & requests page to match url.

- src/components/Account/ResourceList/ListActions/ExportButton/index.js
- src/components/Account/ResourceList/ListActions/style.module.css
- src/components/Interactive/AddToCalendar/index.js
- src/static/css/global.css
- src/tests/components/Account/ResourceList/ListActions/ExportButton/index.test.js
Adds a border around dropdowns. Also fixes button click so it will toggle on and off, instead of always setting to visible on click.
> LW-959 Modify dropdown styling.

- src/components/Contentful/Floor/presenter.js
- src/components/Contentful/FloorList/presenter.js
- src/tests/components/Contentful/Floor/presenter.test.js
- src/tests/components/Contentful/FloorList/presenter.test.js
> LW-977 Add page alerts to floors.

- src/components/Contentful/Alert/alertHelpers.js
- src/components/Contentful/Alert/style.module.css
- src/components/Messages/PageAlert/index.js
- src/constants/HelperFunctions.js
- src/tests/components/Contentful/Alert/Global/index.test.js
- src/tests/components/Contentful/Alert/Page/index.test.js
> LW-979 Add yellow alerts.

- src/components/Account/Favorites/Wizard/index.js
- src/components/SubjectList/index.js
- src/tests/components/Account/Favorites/Wizard/index.test.js
- src/tests/components/SubjectList/index.test.js
Change to Contentful model where a flag is being added so subjects must be explicitly marked to be included on Subjects A-Z page.
> LW-988 Hide subjects from A-Z unless they have been marked to be included.

- src/components/Contentful/Related/index.js
- src/components/Contentful/StaticContent/Alert/index.js
- src/components/Contentful/StaticContent/Sidebar/index.js
- src/components/Contentful/StaticContent/Sidebar/presenter.js
- src/components/DatabaseList/index.js
- src/components/DatabaseList/presenter.js
- src/tests/components/Contentful/StaticContent/Alert/index.test.js
- src/tests/components/Contentful/StaticContent/Alert/presenter.test.js
- src/tests/components/Contentful/StaticContent/Sidebar/index.test.js
- src/tests/components/Contentful/StaticContent/Sidebar/presenter.test.js
- src/tests/components/DatabaseList/index.test.js
- src/tests/components/DatabaseList/presenter.test.js
Also unit tests on some components that didn't have any.
> LW-1040 Add Contentful content to Databases page

- scripts/package.json
- scripts/yarn.lock
- yarn.lock
Closes #908 
Closes #931 
Closes #932 
Closes #939
> Update dependencies based on dependebot.

- src/components/Interactive/Facet/presenter.js
Update to the Facet component to replace spaces with an underscore
> replace facet ID space with underscore

- src/components/Contentful/ColumnPage/Section/index.js
- src/components/Contentful/ColumnPage/presenter.js
- src/components/Layout/Navigation/DropDown/index.js
There was an extra level of nested records that was completely unnecessary. ¯\\\_(ツ)_/¯
Refactor Section into its own file instead of cramming it in with the page presenter file.
> LW-998 Remove redundancy with navigation model.

- .codeclimate.yml
Changes threshold for method size and duplication, because these are particularly problematic in React when composing presentational components (e.g. "large" functions) or specifying props (common "duplication").
> Update code climate config to newer syntax.

- src/components/Contentful/Database/index.js
- src/components/Contentful/Database/presenter.js
- src/shared/ContentfulLibs.js
- src/tests/components/Contentful/Database/index.test.js
- src/tests/components/Contentful/Database/presenter.test.js
Also adds unit tests for this page.
> LW-1096 Fix links with no explicit title not displaying on database page.

- src/components/Contentful/News/presenter.js
- src/components/EventCard/index.js
- src/components/ExhibitCard/index.js
- src/components/Home/Exhibits/presenter.js
- src/components/Image/index.js
- src/components/Image/presenter.js
- src/components/NewsCard/index.js
BONUS: Query the Contentful image API with the actual upper bounds of the image on the page so we aren't sending them over at a higher resolution than necessary.
> LW-1115 Lazy load images

- src/components/Contentful/ModalImage/index.js
- src/components/Contentful/ModalImage/style.module.css
- src/components/DynamicPages/RoomReservations/MeetingSpacesTable/index.js
- src/components/DynamicPages/RoomReservations/index.js
- src/components/SpaceCard/index.js
Also cleans up styling for image modal so it is centered on the screen. (Particularly for mobile.)
And fixed a bug causing the page to crash if you had visited another dynamic page beforehand. 😄
> LW-1120 Support separate thumbnail image for spaces.

- .github/dependabot.yml
- yarn.lock
Dependabot suggested the yarn change. Added a config so it will target the right branch going forward.
Closes #977
> Update dependency. Configure dependabot.
