CHANGELOG.md, src/components/Image/index.js, src/components/Image/presenter.js, src/components/LoanResources/illiadActions.js, src/tests/components/Image/presenter.test.js
- Images now handle errors (like 404) and render null instead of a broken image link
- Buttons on the items page should now link no matter where you click on it
=> Image and Button cleanup

src/components/App/Rewrite/redirectRoutes.js
* library.nd.edu/ill should point to https://nd.illiad.oclc.org/illiad/IND/illiad.dll
* library.nd.edu/docdel -> https://nd.illiad.oclc.org/illiad/IND/illiad.dll
* library.nd.edu/specialists -> https://directory.library.nd.edu/directory/subjects
* library.nd.edu/catalog -> http://factotum.library.nd.edu/utilities/search/ndu/nd_campus
* library.nd.edu/onesearch -> http://factotum.library.nd.edu/utilities/search/ndu/onesearch
=> Redirect urls from Lauren

src/reducers/search.js
The users local search preference was not always being honored. The problem specifically exhibited itself on initial page load, if on a page that never fired any actions that the search reducer cared about (ex: the root page). This was due to the fact that the initial state in the reducer was not applying the rules that we specified, and no other actions were getting called to apply those rules.
Changes:
- Changed the default state to apply the rules defined in setSearchType
- Changed the default state searchType to null. Nothing should officially set this value except for the setSearchType function, so setting it to null initially should hopefully indicate a problem if we forget to call setSearchType in the future.
=> Bugfix: Search preferences

src/components/SearchDrawer/presenter.js
Comment can’t be empty, but needs to be hidden when closed.
=> Hide search drawer image on homepage when closed

src/components/Hours/Current/collapsed_presenter.js, src/components/Hours/Current/expanded_presenter.js, src/components/Hours/Current/index.js, src/components/Hours/InlineContainer/index.js, src/components/Hours/Page/index.js
This contains necessary code changes to fix missing Monday data and "Today: undefined" bugs on the hours page. This does require data changes in libcal before it will be fully fixed. Changes:
- The API will now always return an array for blocks of hours. Changed components to read through the array of hours blocks to see if any of them mean the location is open
- Was getting warnings about how children were passed into the InlineContainer for hours. Some components were sending arrays. We likely shouldn't need to create expectations on children here since we never consume them in anyway other than to just render them as is. Removed it from the proptypes
- Changed the naming of the export in the hours InlineContainer to be a little more descriptive, just so that it's a little quicker to …
=> Bugfix case of the mondays

CHANGELOG.md, src/components/Hours/Current/index.js, src/components/Hours/Page/index.js
- Add math library to hours page
- Fix safari coloring, was parsing as UTC instead of local time zone
=> Math Library + Safari Fix

src/components/Courses/index.js, src/tests/components/Courses/index.test.js
Creates the test for the Courses/index.js file.  Uses the enzyme wrapper to test the Courses Container based on possible outcomes in the index.js file. Also adds export to the Courses Container class declaration because otherwise it cannot be tested.
Then, tests the mapStateToProps functionality  by using two props, "state" and "ownProp".  Tests with correct data and incorrect data.
=> Mh courses unit test

config/configurationGen.js, package.json, src/components/SearchDrawer/SearchBox/index.js, yarn.lock
We currently have no way to actually track search usage on the new site. This should resolve that by creating a custom Google Analytics tracking event.
Note: This is only tracking the basic search right now. I'm unsure if there's any utility for Kate to track the advanced search.
* Add react-ga for programmatic tracking
* On submission of search form, submit a custom event that details
which search type was selected and the query parameters
=> Add programmatic Google Analytics for search

src/components/Contentful/Page/presenter.js, src/components/Home/News/index.js
Use `servicePoints` field (list) instead of `servicePoint` (single), to allow for multiple points to show on pages
This requires a change in contentful data upon deployment -- it's already been made in dev, and I have a script to update the entries in prod. I did already add the field in prod, just haven't updated the entries yet.
=> Multiple Service Points on Pages

src/components/Hours/Current/expanded_presenter.js, src/components/Hours/Current/index.js
Adds special handling when the close time is at midnight. Also changed spacing of hours. Was causing the text to jumble, making it read incorrect hours when the display text was long, ex: "Wednesday - Thursday"
=> Fix hours color display

src/components/Home/Events/index.js
If the event ends at 0:00, assume it actually ends at the end of the day so add 23:59 to make sure it still displays the right day, but will show up until midnight.
=> Add a day to some event end times

deploy/contentfulMigrations/addServicePointsToDynamicPages.js, src/components/Contentful/StaticContent/Sidebar/presenter.js
- allow multiple service points on dynamic pages
- add migration for this contentful change using [this tool](https://github.com/contentful/migration-cli). The migration will be done before deployment, since we currently have no methodology for pre/post deploy scripts.
=> Multiple service points on Dynamic Pages (courses)

src/components/Home/Events/index.js, src/components/LandingPages/Events/presenter.js, src/static/css/global.css
- update event time display
- remove calendar card
- show both date and time on events
- fix landing page spacing issues
- make sure neither events or news are underlined
=> Event Time Display

src/components/SearchDrawer/PartnerSearchToggle/index.js, src/components/SearchDrawer/PartnerSearchToggle/presenter.js, src/components/SearchDrawer/presenter.js, src/components/SearchDrawer/searchQueryBuilder.js, src/static/css/global.css
Add a Search Partner Libraries toggle for ND Catalog. 
I changed the URLs used for onsearch/ndcatalog search. I couldn't find a difference between the`search.do` and `dlsearch.do` urls. The documentation is very sparse, but it seems like they're used interchangeably.  Mostly I went off what actually happens when you go to onesearch, it's always `search.do` so that simplified the query generation code a bit. I did test this, it seems to work the same as on prod, so no change to users should be visible. Changing the scopes requires the `search.do` url, so it made sense to change everything to conform to one.
=> Search Partner Libraries

src/components/SearchDrawer/searchQueryBuilder.js
Only include dates if they are set by the user. This is a partial fix
to dates incorrectly being added to the second and third free text
fields.
=> INC0149167

src/components/Chat/index.js
This does 2 things.
1.  Stops filling the logs on library_prod with 302 requests.
2.  Allows us to control how the css is done for the chat window.
=> Update how the chat css is done

src/components/Contentful/ContactPoint/index.js, src/components/Contentful/Page/presenter.js, src/components/Contentful/Page/style.css, src/tests/components/Contentful/ContactPoint/index.test.js, src/tests/components/Contentful/Page/presenter.test.js
MOBILE - Rearrange order of items on pathfinder pages on mobile -
hours/location/contact info should be at top, and related pages should
be at the bottom
* Move Contact/Service content to sub component
* Include component in two different places and include a mobile flag
to determine where it should be displayed.
=> LW-143:  Rearrange order of items on pathfinder pages

src/components/Home/Events/index.js
We don't want to use the timezone information from contentful anymore. 
To do this, we must force the strings to be our local timezone BEFORE passing them to a Date object. If, after we force our timezone, they are still in a different timezone (the Date class converted it because it was in a different daylight savings time state than we currently are) we must offset it back to our local time.
=> Don't use timezone info for events

src/components/Home/index.js, src/components/PageTitle/index.js
The page title on the homepage is currently 
Hesburgh Library | Hesburgh Library
It should be 
Hesburgh Libraries
and subpages should be 
New Page | Hesburgh Libraries
=> Fix the page title

src/components/Footer/FooterLinks/index.js, src/components/SiteInfoLink/index.js
Avoid the edge case where being on the site-info page and clicking the
link to site-info again keeps appending the same string.
=> Better SiteInfoLink

src/components/SearchDrawer/searchQueryBuilder.js
The current search box needs to send the basic query to the Deep Link Search file. 
I have changed the box to accommodate this. 
I also updated how we are sending the scope for nd catalog and one search to be the grouped scopes instead of the individual "leaf scopes"  
Unfortunately, we can't send advanced searches to the dlSearch file so we have to have a pretty large branch between the dlSearch.do and the search.do.  
The deep link syntax is necessary because doing a regular search can have too great of a performance affect one primo. Also, the new UI should fix this so we don't have to use the deep link syntax.
IN ADDITION,  in the past we have used factotum to proxy deel link queries.  I am not using that.  I do not think that is an appropriate place to do that anymore.  We may wish …
=> Update query generator.

CHANGELOG.md, src/components/Contentful/Database/presenter.js
Make sure the database pages still work before the new information is added.
Once the new sync is running we can remove this and only use the new version, but to support the change we need both.
=> Database Info Bugfix

src/static/css/global.css
On small screens:
- Remove '•' before time
- time is on it's own line below the date
- date wrapping has the same line-height as date/time line separation
=> Make event landing page date/time more mobile friendly

src/actions/contentful/page.js
The secure page container checks to see if the current slug matches the expected slug and if it doesn't, fetch the page. This makes sense to make sure we're grabbing new page content when coming from another page - but since the error action doesn't have a slug it will never match the expected (either be previous page or null). Thus, infinite loop of requests.
=> Fix infinite requests on non-existant secure pages

deploy/ci/buckets.yml, deploy/ci/config.yml, deploy/ci/resources.yml, deploy/ci/root.yml, deploy/contentfulMigrations/2018.01.29.addDynamicPageAlerts.js, src/components/Contentful/Alert/Page/index.js, src/components/Contentful/Page/columnPresenter.js, src/components/Contentful/StaticContent/Alert/index.js, src/components/Contentful/StaticContent/Alert/presenter.js, src/components/Courses/presenter.js, src/components/Hours/Page/presenter.js, src/components/PersonalInfo/presenter.js, src/components/Settings/presenter.js
Adding a `StaticAlert` component in order to add alerts to static page content, very similar to the `StaticBody` and `StaticSidebar` components.
Adding alerts to ColumnContainer pages as well (eg. /services). 
**NOTE** This PR also includes the changes to the CI to build to dev-staging.
=> Add alerts to dynamic pages

src/actions/personal/alephRenewal.js, src/components/LoanResources/ResourceList/Resource/Actions/index.js, src/components/LoanResources/ResourceList/Resource/Actions/presenter.js, src/components/LoanResources/ResourceList/Resource/index.js, src/components/LoanResources/ResourceList/Resource/presenter.js, src/components/LoanResources/ResourceList/index.js, src/components/LoanResources/ResourceList/presenter.js, src/tests/components/LoanResources/ResourceList/Resource/Actions/index.test.js
When renew all is clicked, ILL items didn't show any message about why they weren't renewed. This adds a message saying "view item in ILL to renew"
This change was quite a bit more complicated than it seemed - the while of items & requests code should be refactored at some point.
I also took this as a time to rename a few classes/variables to make it easier to read and debug.
=> ILL Renew all message

src/components/Contentful/Event/presenter.js, src/static/css/global.css
Also, re-enable presenters on events.
Magic: if you put `overflow: hidden` on a parent with floating children, that parent will grow to the size of it's children.
https://stackoverflow.com/questions/9463069/grow-height-of-parent-div-that-contains-floating-nested-divs
=> Make sure presenter info always has background

src/components/SearchDrawer/presenter.js, src/static/css/global.css
Search box on home page extends below background image for advanced search.
**OLD:**
**NEW:**
=> LW-352 - Search box on home page extends below background image

src/components/Contentful/Page/columnPresenter.js, src/components/DatabaseList/presenter.js, src/shared/ContentfulLibs.js, src/static/css/global.css, src/tests/shared/ContentfulLibs.test.js
Created a helper method to create a common `linkObject` from any contentful entry. This allows us to remove complicated conditionals in presenters when trying to display links, particularly with resource entries, but it can also be used for many others.
=> Show all database links on resources landing page

src/components/Contentful/Event/index.js, src/components/Contentful/News/presenter.js, src/components/Contentful/News/style.css
**LW380:** Users want to see a headline on an individual news story that extends to the full width of the column.
- Add css wrapping class for news. Add css style to set wrapped h1 to 100% width.
**LW366:** Users need to see an en dash between between start and end times on individual events.
- Change regular hyphen/dash to `&ndash;`
=> LW 380 & LW366

src/components/Contentful/News/presenter.js, src/components/Contentful/News/style.css, src/components/PageTitle/index.js
Revised:
Make title width of text column
=> LW-380 Users want to see a headline on an individual news story that extends to the full width of the column.

src/actions/floorSearch.js, src/components/App/index.js, src/components/Contentful/Floor/index.js, src/components/Contentful/Floor/presenter.js, src/components/FloorSearch/index.js, src/components/Navigation/index.js, src/reducers/floorSearch.js, src/reducers/index.js, src/static/css/global.css, src/tests/components/Contentful/Floor/index.test.js, src/tests/components/Contentful/Floor/presenter.test.js
Floor search page takes query params and forwards them to the maps api. If a slug is returned from the API, redirect to that floor page.
The `/floor/[slug]` pages now also take query params and display extra information
- title
- author
- call number
This is a basic implementation so we can have it working to demo Wed/Thurs
Relies on https://github.com/ndlib/usurper_content/pull/57
=> Add floor search page so NUI can redirect here for floor maps

public/index.html
* Google analytics snippet removed. It has been implemented in Google tag manager.
* Monsido script replaced with one provided in LW-392
**Additional:**
* Reordered some of the items in the index.html
* Removed white space from some scripts
* Add user initials to `google-site-verification` metatags for sanity
* Moved `title` tag to top. (Yes it can go before `X-UA-Compatible`.)
* Moved `<noscript/>` text inside the `root` div.
=> LW-363, LW-392 Google Analytics and Monsido scripts

src/static/css/global.css
THIS DOES NOT WORK!  
This implementation follows the css3 draft but as far as I can tell no browsers implement it.  This is similar to the @media speech directive which also does not work! 
I have added this so that someday in the bright future if browsers ever catch up we can all die knowing that we have finally removed the really really annoying < from the screen reader on the website menus. 
https://css-tricks.com/almanac/properties/s/speak/
https://stackoverflow.com/questions/27751738/is-the-css-setting-speaknone-now-equivalent-to-aria-hidden-true
I have also checked chrome, safari and firefox the screen reader read the text in all cases. 
I also learned there is a whole set of properties besides speech that in theory let you control the type of voice, speed, and pauses but I expect …
=> added css cmd to remove from speech

src/actions/personal/loanResources.js
This was setting the store key to be `personal.user.user` while the rest of the code was just accessing `personal.user`
=> fix aleph renewal

src/components/Image/index.js
I added a console log since this is something we want to add to whatever error logging we have in the future.
=> let errored images render so prerender works correctly

src/components/DatabaseList/index.js
There is a rare edge case when the user starts trying to filter the list before the all results have been returned. This fixes that problem of getting the page trapped in the loading dialog.
=> LW-439 Databases A-Z error you type in the search box

src/components/Contentful/Floor/presenter.js, src/static/css/global.css
- Large maps will stay within the column
- Added white frame around information given by onesearch items
=> Floor maps will stay inside the lines

deploy/web/postDeploy.py
In order for the command `yarn build --production` to work, we need to include dev dependencies in the `yarn install` command called from postDeploy.py.
The actual built package is not affected by the extra packages since what is build still comes from the production webpack configuration.
=> Fix build.js to run in post-deploy

deployDevStaging.sh, deployServicesLocal.sh
It deploys the services and has a script to deploy the website.  
NOTE: this is not a final version of this process but more of a guideline you can look at to see how it should function.  We may wish to use these for now and they give an example of what order things need to be run in but eventually they need to be moved to codeBuild + Jenkins/pipeline.  
Also, the exports are intentional.  I want you to have to look at the file before you run it.
=> Add new deploy scripts

src/components/Contentful/News/presenter.js, src/components/Contentful/News/style.css
On News items previously published text was at the top of the page and contact us was contained within the news article body markdown.  The previously published text and contact us info have been combined into their own markdown box and put immediately after the article body.
=> combined previously published and contact us into single markdown box

src/tests/components/APIPresenterFactory/index.test.js, src/tests/components/Hours/Page/index.test.js
I think we need to consider some refactoring work around the APIPresenterFactory now anyway since we have access to error boundaries and part of what it was attempting to do was handle error states.
=> these test break and need to be rewritten or removed in the future

src/components/SearchDrawer/AdvancedSearch/AdvancedSearchField/SearchInput/index.js, src/components/SearchDrawer/AdvancedSearch/AdvancedSearchField/SearchInput/presenter.js, src/components/SearchDrawer/AdvancedSearch/DateField/index.js, src/components/SearchDrawer/AdvancedSearch/DateField/presenter.js, src/components/SearchDrawer/SearchBox/index.js, src/components/SearchDrawer/SearchBox/presenter.js, src/components/SearchDrawer/presenter.js
Input fields in search boxes are slow to respond because they are updating the store on every key press. These changes only update the store when the element loses focus (onBlur) or when the form is submitted without changing focus. (onKeyDown enter)
Applies to both basic search and advanced search.
=> LW-537 Improve Search Box Responsiveness

src/actions/contentful/allAlerts.js, src/actions/contentful/allEvents.js, src/actions/contentful/allNews.js, src/actions/contentful/databaseLetter.js, src/actions/contentful/entry.js, src/actions/contentful/event.js, src/actions/contentful/floor.js, src/actions/contentful/news.js, src/actions/contentful/page.js, src/actions/contentful/servicePoints.js, src/actions/contentful/staticContent.js
We are supposed to be catching errors when fetching from contentful direct and piping the result into an error object, which has a different schema compared to the success object. However, we were frequently only checking for the existence of a response to determine whether there was a success or not, so errors were incorrectly getting marked as "statuses.SUCCESS" and subsequently causing rendering errors since the schema did not match.
=> Fix response validation coming from contentful direct.

src/components/SearchDrawer/AdditionalLinks/index.js, src/components/SearchDrawer/AdvancedSearch/index.js, src/components/SearchDrawer/AdvancedSearch/presenter.js, src/components/SearchDrawer/AdvancedSearch/style.css, src/components/SearchDrawer/SearchOptionList/index.js, src/components/SearchDrawer/index.js, src/components/SearchDrawer/searchQueryBuilder.js, src/constants/searchOptions.js, src/reducers/search.js
- Move searchOptions to constants where it fits in better.
- Add "enableAdvancedSearch" to searchOptions array instead of hard-coding a check on individual pages.
=> LW-567 Add ability to switch search type in advanced search.

src/actions/contentful/allEvents.js, src/actions/contentful/allNews.js, src/actions/contentful/entry.js, src/actions/contentful/event.js, src/actions/contentful/news.js, src/actions/contentful/servicePoints.js, src/actions/contentful/staticContent.js, src/actions/menu.js
Previously fixed on the "page" content type, but I missed the other content types which also specify an include depth.
This can help dramatically reduce the response size and thus improve performance. In the future, we should be very intentional about how deep a certain content type should go and never fetch more than we need.
=> LW-594 Reduce include depth when fetching from contentful.

package.json, src/actions/personal/favorites.js, src/components/Account/Favorites/ManageFavorites/index.js, src/components/Account/Favorites/ManageFavorites/presenter.js, src/components/Account/Favorites/Wizard/SubjectStep/index.js, src/components/Account/Favorites/Wizard/index.js, src/components/Account/Favorites/Wizard/presenter.js, src/components/Account/Favorites/index.js, src/components/Account/Settings/HomePageDisplay/index.js, src/components/DatabaseList/index.js, src/constants/HelperFunctions.js, src/reducers/contentful/databaseLetter.js, src/reducers/personal.js, src/static/css/global.css, src/tests/components/Account/Favorites/FavoritesList/index.test.js, src/tests/components/Account/Favorites/ManageFavorites/index.test.js, src/tests/components/Account/Favorites/Wizard/SubjectStep/index.test.js, src/tests/components/Account/Favorites/Wizard/index.test.js, src/tests/components/Account/Favorites/Wizard/presenter.test.js, yarn.lock
Fixes a number of issues the favorites wizard was having with the newly updated model for subjects. Also enhances the wizard so that it can be reopened for specific steps and will load existing favorites data in order to allow modifying after initial selection. Fixed some formatting issues as well, and added more tests.
=> LW-657 Add modal with all subjects (modify favorites using wizard)

src/components/Contentful/SecurePage/index.js
Reported problem: Secure pages intermittently get stuck on Loading animation.
Technical problem: `mapStateToProps` was not updating `this.props.login` correctly because of some internal optimizations that redux does durring mapStateToProps.
Solution: `this.props.login` is assigned as an immutable object with `Object.assign` instead of directly setting it to `state.personal.login`
https://redux.js.org/faq/react-redux#why-isn-t-my-component-re-rendering-or-my-mapstatetoprops-running
=> Fix intermittent page rendering problem on secure pages

src/components/Contentful/Page/index.js, src/components/Contentful/ServicePoint/index.js, src/components/Librarians/index.js, src/reducers/contentful/page.js, src/reducers/contentful/staticContent.js, src/reducers/librarians.js, src/tests/components/Contentful/Page/index.test.js, src/tests/reducers/contentful/page.test.js, src/tests/reducers/librarians.test.js
In essence, this was happening because when you change pages, the previous page is still loaded in the store. This caused the new page to render the old page for a brief moment, and this triggers a request to fetch librarian info. When the slug updates, it fetches the librarian info for the new slug and a race condition starts.
Simple solution: Don't render anything if the page in the store does not match the route you are on. Wait for the new page to be fetched.
=> Fix incorrect librarians showing up when changing pages.

public/robots.txt
These are dumby "pages" that merely exist so they can be used as preferred locations. They have no content, so we don't want them showing up in search results.
=> Add rbsc and archives to robots.txt.

src/actions/contentful/allEvents.js, src/actions/contentful/allNews.js, src/actions/contentful/branches.js, src/actions/contentful/database.js, src/actions/contentful/entry.js, src/actions/contentful/event.js, src/actions/contentful/floor.js, src/actions/contentful/internalLink.js, src/actions/contentful/news.js, src/actions/contentful/page.js, src/actions/contentful/servicePoints.js, src/actions/contentful/staticContent.js, src/actions/contentful/subjects.js, src/actions/menu.js, src/constants/HelperFunctions.js, src/tests/actions/contentful/branches.test.js, src/tests/actions/contentful/database.test.js, src/tests/actions/contentful/subjects.test.js, src/tests/actions/menu.test.js
Requests to Contentful Direct were still being cached regardless of whether they had the preview flag or not. Since previews could be cached, this meant Contentful users could not get quick feedback from the preview feature as intended.
Sending all previews to livequery will greatly reduce the cache time (currently 30 seconds), which should be a much better experience when trying to rapidly prototype changes in Contentful.
=> LW-706 Send Contentful preview requests to livequery to reduce cache time.

package.json, src/actions/contentful/allAlerts.js, src/actions/menu.js, src/components/App/index.js, src/components/Contentful/ColumnPage/index.js, src/components/Contentful/News/index.js, src/components/FloorSearch/Empty/index.js, src/components/Home/News/index.js, src/components/Hours/Page/index.js, src/components/LandingPages/News/index.js, src/components/Layout/PageWrapper/index.js, src/constants/HelperFunctions.js, src/tests/actions/contentful/branches.test.js, src/tests/actions/contentful/database.test.js, src/tests/actions/contentful/subjects.test.js, src/tests/components/Layout/PageWrapper/index.test.js, yarn.lock
A new endpoint was created in Contentful Direct to serve up preview requests with a much lower cache time, since the caching was interfering with the need for quick feedback that previews demand. This change calls that endpoint, as well as fixes a few places on the site that did not check for the previews flag at all.
=> LW-706 Fix preview of Contentful content universally

src/actions/search.js, src/components/SearchPage/SearchPager/index.js, src/components/SearchPage/presenter.js, src/static/css/global.css, src/tests/components/LandingPages/Events/Past/index.test.js
This also includes a usability improvement that will display the paging links for previous pages even when there are no results. This is helpful when users land on a page past the final result (due to inaccurate result counts), so they can try the page before it instead of returning to page 1 by running the search again.
=> LW-792 Include search results that Google filters by default.

src/actions/contentful/allEvents.js, src/actions/contentful/allNews.js, src/components/LandingPages/Events/Wrapper/index.js, src/static/css/global.css
Previously was not sorting after changing the filter, and was getting duplicates due to some circular logic. Doing a shallower fetch from Contentful prevents this.
=> Fix events not sorting and filtering correctly.

src/components/Hours/Current/index.js, src/tests/components/Hours/Current/index.test.js
There was an issue where the background of an hours would show up as red (as if the location was closed) on initial render. This is because the status wasn't getting updated until "tick" was called, which would not happen until the next render cycle. This fix resolves this for a better visual experience.
=> Fix hours status delayed

package.json, scripts/yarn.lock, yarn.lock
* Remove lodash from `scripts` dependencies.
* Remove snyk from `package.json` since we aren't using it.
* Upgrade several dependencies in root yarn.lock.
The resolutions block of `package.json` allows us to enforce minimum versions for *indirect* dependencies of our project. This is useful for eliminating security risk when our direct dependencies do not necessarily keep up-to-date with all of their own dependencies.
For instance, we never want to require lodash directly, but several of our included libraries do. This lets us force lodash to resolve to ^4.17.15 regardless of how outdated the lodash version might be in some other library's package.json.
=> Upgrade dependencies to eliminate security vulnerabilities.

scripts/buildConfig.js
This allows the pipeline to tell us when it is appropriate to mock out urls for the various services, versus when valid export paths in AWS are required for a successful build.
=> Update build so it relies on environment variable for when to fake service urls.

.hound.yml
This should fix hound throwing errors when it tries to run on our PRs.
=> Upgrade eslint version for hound to match our installed package version.

src/actions/personal/favorites.js, src/actions/personal/settings.js, src/components/Account/Favorites/Wizard/index.js, src/tests/actions/personal/favorites.test.js, src/tests/components/Account/Favorites/Wizard/index.test.js
Simply put, when searching for databases to include in favorites, include items with the "externalLink" content type if they have the `canFavorite` flag set to true.
=> LW-759 Add favoriting certain external links.

src/actions/personal/token.js
`authClient.token.parseFromUrl()` is throwing an exception (basically saying unauthorized) because departmental accounts are not included in our application profile. It was simply failing to update the API call status in the store for this scenario.
=> LW-869 Fix authentication errors causing hung api status.

package.json, src/components/LibMarkdown/index.js, src/tests/components/LibMarkdown/index.test.js, yarn.lock
The library maintainer was unresponsive to my PR, so I forked the project so we can render how we want to. This will give content editors more consistency between the Contentful preview and how content displays on the site.
=> LW-906 Switch markdown-to-jsx to forked version.

package.json, yarn.lock
react-dev-utils v10.1.0 introduced support for WebSocket Secure (WSS). Since we are running on https, it seems proper to use WSS... But this introduced an issue with our development server setup. Periodically, the web server will throw an exception during compile and disconnect if not caught.
Judging by [this issue](https://github.com/webpack/webpack-dev-server/issues/1642), it has something to do with proxying the requests. I tried updating http-proxy-middleware to the latest, but that didn't help.
I'm still not sure if the issue is with another library or our implementation in the start.js script, but either way, this works around the issue. Essentially, this downgrade reverts to plain unencrypted WS, but since we're only running this on localhost in the first place I don't think it's …
=> Downgrade react-dev-utils to get around a dev server crashing issue.

src/components/DatabaseList/Databases/BestBets/index.js, src/tests/components/DatabaseList/Databases/BestBets/index.test.js
Subjects have a field called "id" since we needed a user-friendly identifier for query strings and `sys.id` isn't modifiable. We just have to actually use the right id in the right place. :)
=> Fix issue with best bets for certain subjects.

src/components/Chat/index.js, src/tests/components/Chat/index.test.js
The iframe approach wouldn't really work because we need to customize the display when chat is offline. The only way to identify that is to use libraryh3lp's built-in customization, which requires that we call their script instead of just calling the iframe directly.
Ultimately the script still embeds an iframe if chat is online, but it lets us specify custom HTML (in their admin UI) when it is offline.
=> LW-1064 Refactor chat so it will show custom offline text.

src/components/App/index.js
Lazy loading all these components introduced occasional errors in Sentry, although we haven't gotten any reports of users experiencing issues as a result. Regardless, it's pretty clear that the code-splitting introduced from lazy loading caused these errors, so I think it's safer to remove this for now.
We can revisit when the service worker model is functional.
=> Remove lazy load because there are intermittent Sentry errors.

src/actions/contentful/staticContent.js, src/components/LandingPages/StudySpaces/presenter.js, src/components/LandingPages/Wrapper/index.js, src/components/LandingPages/Wrapper/presenter.js, src/constants/HelperFunctions.js, src/tests/components/LandingPages/StudySpaces/index.test.js, src/tests/components/LandingPages/StudySpaces/presenter.test.js, src/tests/components/LandingPages/Wrapper/index.test.js, src/tests/components/LandingPages/Wrapper/presenter.test.js
This change allows all pages which use the LandingPageWrapper component to get a DynamicPage from Contentful simply by passing in the slug as a prop.
Fixed an issue with sorting integers so they sort naturally instead of as strings.
=> LW-1121 Add dynamic page for study spaces and sort listing.

src/components/Account/Preferences/Wizard/index.js, src/tests/components/Account/Preferences/Wizard/index.test.js
Content model changed, and this field no longer exists as it isn't needed, so everything was getting filtered out. 🙃
=> LW-1137 Fix subjects not displaying on favorites wizard.

src/static/css/global.css
Some higher specificity overrides and moved some styles to a different media query so all the navigation styles change to mobile at the same point.
=> LW-1127 Fix navigation styling (especially for Safari.)

public/index.html, src/components/Chat/index.js, src/components/Layout/Footer/FooterInfo/ChatModal/index.js, src/static/css/global.css, src/tests/components/Chat/index.test.js, src/tests/components/Layout/Footer/FooterInfo/ChatModal/index.test.js
Sometimes opening the chat box didn't work, I think because of script execution order and a race condition. Ultimately all that the external javascript did was insert an iframe in the `.libraryh3lp` element, so I just cut that out of the process and placed the iframe directly in there. This seems to be more reliable.
=> LW-1141 Fix chat box not showing on chat page.
